baseURL = "https://pmantz.netlify.app/"
languageCode = "en-us"
theme = "hyde"
title = "My site"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-0e"
